version: "3"
services:
  mongo:
    container_name: css
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mongocss
      - MONGO_INITDB_ROOT_USERNAME=mongocss
      - MONGO_INITDB_ROOT_PASSWORD=mongocss
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo:/data/db
