version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
        - MONGO_INITDB_DATABASE=day-challenge
        - MONGO_INITDB_ROOT_USERNAME=day-challenge
        - MONGO_INITDB_ROOT_PASSWORD=day-challenge
    volumes:
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        - ./mongo:/data/db
