name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]
    
    steps:
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.1.0
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: run tests, lint
      run: |
        yarn install
        yarn test
        yarn lint
      env:
        CI: true
        TEST_MONGO_PORT: 27017 
    
    - name: Jest Code Coverage Report
      uses: ziishaned/jest-reporter-action@0.1.1
      with:
        # Github token
        github-token: ${{ secrets.JEST }}
        # Specify a command to run the tests
